//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TournamentStat.Applications.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TournamentStat.Applications.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nomination: .
        /// </summary>
        internal static string Out_Sheet_Nomination_Prefix {
            get {
                return ResourceManager.GetString("Out_Sheet_Nomination_Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participants.
        /// </summary>
        internal static string Out_Sheet_Participants {
            get {
                return ResourceManager.GetString("Out_Sheet_Participants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stat.
        /// </summary>
        internal static string Out_Sheet_Stat {
            get {
                return ResourceManager.GetString("Out_Sheet_Stat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage.
        /// </summary>
        internal static string TournamentCriterion_Damage {
            get {
                return ResourceManager.GetString("TournamentCriterion_Damage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage + Potential Damage Received.
        /// </summary>
        internal static string TournamentCriterion_DamageWithArmor {
            get {
                return ResourceManager.GetString("TournamentCriterion_DamageWithArmor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage + Assited Damage.
        /// </summary>
        internal static string TournamentCriterion_DamageWithAssist {
            get {
                return ResourceManager.GetString("TournamentCriterion_DamageWithAssist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frags.
        /// </summary>
        internal static string TournamentCriterion_Frags {
            get {
                return ResourceManager.GetString("TournamentCriterion_Frags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Win Percent.
        /// </summary>
        internal static string TournamentCriterion_WinPercent {
            get {
                return ResourceManager.GetString("TournamentCriterion_WinPercent", resourceCulture);
            }
        }
    }
}
