//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WotDossier.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WotDossier.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap award_images {
            get {
                object obj = ResourceManager.GetObject("award_images", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battle Hero.
        /// </summary>
        public static string Column_BattleAwards_BattleHero {
            get {
                return ResourceManager.GetString("Column_BattleAwards_BattleHero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brothers In Arms.
        /// </summary>
        public static string Column_BattleAwards_BrothersInArms {
            get {
                return ResourceManager.GetString("Column_BattleAwards_BrothersInArms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confederate.
        /// </summary>
        public static string Column_BattleAwards_Confederate {
            get {
                return ResourceManager.GetString("Column_BattleAwards_Confederate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cool Headed.
        /// </summary>
        public static string Column_BattleAwards_CoolHeaded {
            get {
                return ResourceManager.GetString("Column_BattleAwards_CoolHeaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crucial Contribution.
        /// </summary>
        public static string Column_BattleAwards_CrucialContribution {
            get {
                return ResourceManager.GetString("Column_BattleAwards_CrucialContribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defender.
        /// </summary>
        public static string Column_BattleAwards_Defender {
            get {
                return ResourceManager.GetString("Column_BattleAwards_Defender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invader.
        /// </summary>
        public static string Column_BattleAwards_Invader {
            get {
                return ResourceManager.GetString("Column_BattleAwards_Invader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lucky Devil.
        /// </summary>
        public static string Column_BattleAwards_LuckyDevil {
            get {
                return ResourceManager.GetString("Column_BattleAwards_LuckyDevil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patrol Duty.
        /// </summary>
        public static string Column_BattleAwards_PatrolDuty {
            get {
                return ResourceManager.GetString("Column_BattleAwards_PatrolDuty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scout.
        /// </summary>
        public static string Column_BattleAwards_Scout {
            get {
                return ResourceManager.GetString("Column_BattleAwards_Scout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sniper.
        /// </summary>
        public static string Column_BattleAwards_Sniper {
            get {
                return ResourceManager.GetString("Column_BattleAwards_Sniper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spartan.
        /// </summary>
        public static string Column_BattleAwards_Spartan {
            get {
                return ResourceManager.GetString("Column_BattleAwards_Spartan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steel Wall.
        /// </summary>
        public static string Column_BattleAwards_SteelWall {
            get {
                return ResourceManager.GetString("Column_BattleAwards_SteelWall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Gun.
        /// </summary>
        public static string Column_BattleAwards_TopGun {
            get {
                return ResourceManager.GetString("Column_BattleAwards_TopGun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battles.
        /// </summary>
        public static string Column_Battles_Battles {
            get {
                return ResourceManager.GetString("Column_Battles_Battles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draws.
        /// </summary>
        public static string Column_Battles_Draws {
            get {
                return ResourceManager.GetString("Column_Battles_Draws", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draws %.
        /// </summary>
        public static string Column_Battles_DrawsPercent {
            get {
                return ResourceManager.GetString("Column_Battles_DrawsPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lost.
        /// </summary>
        public static string Column_Battles_Lost {
            get {
                return ResourceManager.GetString("Column_Battles_Lost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lost %.
        /// </summary>
        public static string Column_Battles_LostPercent {
            get {
                return ResourceManager.GetString("Column_Battles_LostPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survived.
        /// </summary>
        public static string Column_Battles_Survived {
            get {
                return ResourceManager.GetString("Column_Battles_Survived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survived And Won.
        /// </summary>
        public static string Column_Battles_SurvivedAndWon {
            get {
                return ResourceManager.GetString("Column_Battles_SurvivedAndWon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survived And Won %.
        /// </summary>
        public static string Column_Battles_SurvivedAndWonPercent {
            get {
                return ResourceManager.GetString("Column_Battles_SurvivedAndWonPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survived %.
        /// </summary>
        public static string Column_Battles_SurvivedPercent {
            get {
                return ResourceManager.GetString("Column_Battles_SurvivedPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Won.
        /// </summary>
        public static string Column_Battles_Won {
            get {
                return ResourceManager.GetString("Column_Battles_Won", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WonPercent.
        /// </summary>
        public static string Column_Battles_WonPercent {
            get {
                return ResourceManager.GetString("Column_Battles_WonPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Damage Dealt.
        /// </summary>
        public static string Column_Damage_AverageDamageDealt {
            get {
                return ResourceManager.GetString("Column_Damage_AverageDamageDealt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage Dealt.
        /// </summary>
        public static string Column_Damage_DamageDealt {
            get {
                return ResourceManager.GetString("Column_Damage_DamageDealt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage Per Hit.
        /// </summary>
        public static string Column_Damage_DamagePerHit {
            get {
                return ResourceManager.GetString("Column_Damage_DamagePerHit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage Ratio.
        /// </summary>
        public static string Column_Damage_DamageRatio {
            get {
                return ResourceManager.GetString("Column_Damage_DamageRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage Taken.
        /// </summary>
        public static string Column_Damage_DamageTaken {
            get {
                return ResourceManager.GetString("Column_Damage_DamageTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billotte.
        /// </summary>
        public static string Column_Epics_Billotte {
            get {
                return ResourceManager.GetString("Column_Epics_Billotte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boelter.
        /// </summary>
        public static string Column_Epics_Boelter {
            get {
                return ResourceManager.GetString("Column_Epics_Boelter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BrunoPietro.
        /// </summary>
        public static string Column_Epics_BrunoPietro {
            get {
                return ResourceManager.GetString("Column_Epics_BrunoPietro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Burda.
        /// </summary>
        public static string Column_Epics_Burda {
            get {
                return ResourceManager.GetString("Column_Epics_Burda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De Langlade.
        /// </summary>
        public static string Column_Epics_DeLanglade {
            get {
                return ResourceManager.GetString("Column_Epics_DeLanglade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dumitru.
        /// </summary>
        public static string Column_Epics_Dumitru {
            get {
                return ResourceManager.GetString("Column_Epics_Dumitru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fadin.
        /// </summary>
        public static string Column_Epics_Fadin {
            get {
                return ResourceManager.GetString("Column_Epics_Fadin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Halonen.
        /// </summary>
        public static string Column_Epics_Halonen {
            get {
                return ResourceManager.GetString("Column_Epics_Halonen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heroes Of Raseiniai.
        /// </summary>
        public static string Column_Epics_HeroesOfRaseiniai {
            get {
                return ResourceManager.GetString("Column_Epics_HeroesOfRaseiniai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kolobanov.
        /// </summary>
        public static string Column_Epics_Kolobanov {
            get {
                return ResourceManager.GetString("Column_Epics_Kolobanov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lafayette-Pool.
        /// </summary>
        public static string Column_Epics_LafayettePool {
            get {
                return ResourceManager.GetString("Column_Epics_LafayettePool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lehvaslaiho.
        /// </summary>
        public static string Column_Epics_Lehvaslaiho {
            get {
                return ResourceManager.GetString("Column_Epics_Lehvaslaiho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nikolas.
        /// </summary>
        public static string Column_Epics_Nikolas {
            get {
                return ResourceManager.GetString("Column_Epics_Nikolas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orlik.
        /// </summary>
        public static string Column_Epics_Orlik {
            get {
                return ResourceManager.GetString("Column_Epics_Orlik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oskin.
        /// </summary>
        public static string Column_Epics_Oskin {
            get {
                return ResourceManager.GetString("Column_Epics_Oskin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pascucci.
        /// </summary>
        public static string Column_Epics_Pascucci {
            get {
                return ResourceManager.GetString("Column_Epics_Pascucci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radley-Walters.
        /// </summary>
        public static string Column_Epics_RadleyWalters {
            get {
                return ResourceManager.GetString("Column_Epics_RadleyWalters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamada Yoshio.
        /// </summary>
        public static string Column_Epics_TamadaYoshio {
            get {
                return ResourceManager.GetString("Column_Epics_TamadaYoshio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarczay.
        /// </summary>
        public static string Column_Epics_Tarczay {
            get {
                return ResourceManager.GetString("Column_Epics_Tarczay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battles.
        /// </summary>
        public static string Column_Frags_Battles {
            get {
                return ResourceManager.GetString("Column_Frags_Battles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BeastFrags.
        /// </summary>
        public static string Column_Frags_BeastFrags {
            get {
                return ResourceManager.GetString("Column_Frags_BeastFrags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frags.
        /// </summary>
        public static string Column_Frags_Frags {
            get {
                return ResourceManager.GetString("Column_Frags_Frags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FragsPerBattle.
        /// </summary>
        public static string Column_Frags_FragsPerBattle {
            get {
                return ResourceManager.GetString("Column_Frags_FragsPerBattle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KillDeathRatio.
        /// </summary>
        public static string Column_Frags_KillDeathRatio {
            get {
                return ResourceManager.GetString("Column_Frags_KillDeathRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Frags.
        /// </summary>
        public static string Column_Frags_MaxFrags {
            get {
                return ResourceManager.GetString("Column_Frags_MaxFrags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SinaiFrags.
        /// </summary>
        public static string Column_Frags_SinaiFrags {
            get {
                return ResourceManager.GetString("Column_Frags_SinaiFrags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tier8Frags.
        /// </summary>
        public static string Column_Frags_Tier8Frags {
            get {
                return ResourceManager.GetString("Column_Frags_Tier8Frags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon.
        /// </summary>
        public static string Column_Header_Icon {
            get {
                return ResourceManager.GetString("Column_Header_Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tank.
        /// </summary>
        public static string Column_Header_Tank {
            get {
                return ResourceManager.GetString("Column_Header_Tank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tier.
        /// </summary>
        public static string Column_Header_Tier {
            get {
                return ResourceManager.GetString("Column_Header_Tier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is premium tank.
        /// </summary>
        public static string Column_MasterTanker_IsPremium {
            get {
                return ResourceManager.GetString("Column_MasterTanker_IsPremium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abrams.
        /// </summary>
        public static string Column_Medals_Abrams {
            get {
                return ResourceManager.GetString("Column_Medals_Abrams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carius.
        /// </summary>
        public static string Column_Medals_Carius {
            get {
                return ResourceManager.GetString("Column_Medals_Carius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ekins.
        /// </summary>
        public static string Column_Medals_Ekins {
            get {
                return ResourceManager.GetString("Column_Medals_Ekins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kay.
        /// </summary>
        public static string Column_Medals_Kay {
            get {
                return ResourceManager.GetString("Column_Medals_Kay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Knispel.
        /// </summary>
        public static string Column_Medals_Knispel {
            get {
                return ResourceManager.GetString("Column_Medals_Knispel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lavrinenko.
        /// </summary>
        public static string Column_Medals_Lavrinenko {
            get {
                return ResourceManager.GetString("Column_Medals_Lavrinenko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leclerk.
        /// </summary>
        public static string Column_Medals_Leclerk {
            get {
                return ResourceManager.GetString("Column_Medals_Leclerk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poppel.
        /// </summary>
        public static string Column_Medals_Poppel {
            get {
                return ResourceManager.GetString("Column_Medals_Poppel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture Points.
        /// </summary>
        public static string Column_Performance_CapturePoints {
            get {
                return ResourceManager.GetString("Column_Performance_CapturePoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defence Points.
        /// </summary>
        public static string Column_Performance_DefencePoints {
            get {
                return ResourceManager.GetString("Column_Performance_DefencePoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hit Ratio.
        /// </summary>
        public static string Column_Performance_HitRatio {
            get {
                return ResourceManager.GetString("Column_Performance_HitRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hits.
        /// </summary>
        public static string Column_Performance_Hits {
            get {
                return ResourceManager.GetString("Column_Performance_Hits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shots.
        /// </summary>
        public static string Column_Performance_Shots {
            get {
                return ResourceManager.GetString("Column_Performance_Shots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tanks Spotted.
        /// </summary>
        public static string Column_Performance_TanksSpotted {
            get {
                return ResourceManager.GetString("Column_Performance_TanksSpotted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Damage.
        /// </summary>
        public static string Column_Ratings_AverageDamage {
            get {
                return ResourceManager.GetString("Column_Ratings_AverageDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battles.
        /// </summary>
        public static string Column_Ratings_Battles {
            get {
                return ResourceManager.GetString("Column_Ratings_Battles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage Rating Rev1.
        /// </summary>
        public static string Column_Ratings_DamageRatingRev1 {
            get {
                return ResourceManager.GetString("Column_Ratings_DamageRatingRev1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eff Rating.
        /// </summary>
        public static string Column_Ratings_EffRating {
            get {
                return ResourceManager.GetString("Column_Ratings_EffRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiev Armor Rating.
        /// </summary>
        public static string Column_Ratings_KievArmorRating {
            get {
                return ResourceManager.GetString("Column_Ratings_KievArmorRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KillDeathRatio.
        /// </summary>
        public static string Column_Ratings_KillDeathRatio {
            get {
                return ResourceManager.GetString("Column_Ratings_KillDeathRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark Of Mastery.
        /// </summary>
        public static string Column_Ratings_MarkOfMastery {
            get {
                return ResourceManager.GetString("Column_Ratings_MarkOfMastery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Winrate.
        /// </summary>
        public static string Column_Ratings_Winrate {
            get {
                return ResourceManager.GetString("Column_Ratings_Winrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WN6.
        /// </summary>
        public static string Column_Ratings_WN6 {
            get {
                return ResourceManager.GetString("Column_Ratings_WN6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invincible Longest.
        /// </summary>
        public static string Column_Series_InvincibleLongest {
            get {
                return ResourceManager.GetString("Column_Series_InvincibleLongest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invincible Progress.
        /// </summary>
        public static string Column_Series_InvincibleProgress {
            get {
                return ResourceManager.GetString("Column_Series_InvincibleProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master Gunner Longest.
        /// </summary>
        public static string Column_Series_MasterGunnerLongest {
            get {
                return ResourceManager.GetString("Column_Series_MasterGunnerLongest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master Gunner Progress.
        /// </summary>
        public static string Column_Series_MasterGunnerProgress {
            get {
                return ResourceManager.GetString("Column_Series_MasterGunnerProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reaper Longest.
        /// </summary>
        public static string Column_Series_ReaperLongest {
            get {
                return ResourceManager.GetString("Column_Series_ReaperLongest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reaper Progress.
        /// </summary>
        public static string Column_Series_ReaperProgress {
            get {
                return ResourceManager.GetString("Column_Series_ReaperProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sharpshooter Longest.
        /// </summary>
        public static string Column_Series_SharpshooterLongest {
            get {
                return ResourceManager.GetString("Column_Series_SharpshooterLongest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sharpshooter Progress.
        /// </summary>
        public static string Column_Series_SharpshooterProgress {
            get {
                return ResourceManager.GetString("Column_Series_SharpshooterProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survivor Longest.
        /// </summary>
        public static string Column_Series_SurvivorLongest {
            get {
                return ResourceManager.GetString("Column_Series_SurvivorLongest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survivor Progress.
        /// </summary>
        public static string Column_Series_SurvivorProgress {
            get {
                return ResourceManager.GetString("Column_Series_SurvivorProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bombardier.
        /// </summary>
        public static string Column_SpecialAwards_Bombardier {
            get {
                return ResourceManager.GetString("Column_SpecialAwards_Bombardier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hunter.
        /// </summary>
        public static string Column_SpecialAwards_Hunter {
            get {
                return ResourceManager.GetString("Column_SpecialAwards_Hunter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invincible.
        /// </summary>
        public static string Column_SpecialAwards_Invincible {
            get {
                return ResourceManager.GetString("Column_SpecialAwards_Invincible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kamikaze.
        /// </summary>
        public static string Column_SpecialAwards_Kamikaze {
            get {
                return ResourceManager.GetString("Column_SpecialAwards_Kamikaze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MouseTrap.
        /// </summary>
        public static string Column_SpecialAwards_MouseTrap {
            get {
                return ResourceManager.GetString("Column_SpecialAwards_MouseTrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PattonValley.
        /// </summary>
        public static string Column_SpecialAwards_PattonValley {
            get {
                return ResourceManager.GetString("Column_SpecialAwards_PattonValley", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raider.
        /// </summary>
        public static string Column_SpecialAwards_Raider {
            get {
                return ResourceManager.GetString("Column_SpecialAwards_Raider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranger.
        /// </summary>
        public static string Column_SpecialAwards_Ranger {
            get {
                return ResourceManager.GetString("Column_SpecialAwards_Ranger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reaper.
        /// </summary>
        public static string Column_SpecialAwards_Reaper {
            get {
                return ResourceManager.GetString("Column_SpecialAwards_Reaper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sharpshooter.
        /// </summary>
        public static string Column_SpecialAwards_Sharpshooter {
            get {
                return ResourceManager.GetString("Column_SpecialAwards_Sharpshooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sinai.
        /// </summary>
        public static string Column_SpecialAwards_Sinai {
            get {
                return ResourceManager.GetString("Column_SpecialAwards_Sinai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survivor.
        /// </summary>
        public static string Column_SpecialAwards_Survivor {
            get {
                return ResourceManager.GetString("Column_SpecialAwards_Survivor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Battle Time.
        /// </summary>
        public static string Column_Time_AverageBattleTime {
            get {
                return ResourceManager.GetString("Column_Time_AverageBattleTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Battle.
        /// </summary>
        public static string Column_Time_LastBattle {
            get {
                return ResourceManager.GetString("Column_Time_LastBattle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play Time.
        /// </summary>
        public static string Column_Time_PlayTime {
            get {
                return ResourceManager.GetString("Column_Time_PlayTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average XP.
        /// </summary>
        public static string Column_XP_AverageXP {
            get {
                return ResourceManager.GetString("Column_XP_AverageXP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum XP.
        /// </summary>
        public static string Column_XP_MaximumXP {
            get {
                return ResourceManager.GetString("Column_XP_MaximumXP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total XP.
        /// </summary>
        public static string Column_XP_TotalXP {
            get {
                return ResourceManager.GetString("Column_XP_TotalXP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Experience per Battle: .
        /// </summary>
        public static string Common_AvgExperience {
            get {
                return ResourceManager.GetString("Common_AvgExperience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battle Performance.
        /// </summary>
        public static string Common_BattlePerformance {
            get {
                return ResourceManager.GetString("Common_BattlePerformance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battles Participated: .
        /// </summary>
        public static string Common_BattlesParticipated {
            get {
                return ResourceManager.GetString("Common_BattlesParticipated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battles Survived:.
        /// </summary>
        public static string Common_BattlesSurvived {
            get {
                return ResourceManager.GetString("Common_BattlesSurvived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture Points: .
        /// </summary>
        public static string Common_CapturePoints {
            get {
                return ResourceManager.GetString("Common_CapturePoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days in clan: .
        /// </summary>
        public static string Common_Clan_DaysInClan {
            get {
                return ResourceManager.GetString("Common_Clan_DaysInClan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enrolled: .
        /// </summary>
        public static string Common_Clan_Enrolled {
            get {
                return ResourceManager.GetString("Common_Clan_Enrolled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position: .
        /// </summary>
        public static string Common_Clan_Position {
            get {
                return ResourceManager.GetString("Common_Clan_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage Caused: .
        /// </summary>
        public static string Common_DamageCaused {
            get {
                return ResourceManager.GetString("Common_DamageCaused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data as of: .
        /// </summary>
        public static string Common_DataUpdate {
            get {
                return ResourceManager.GetString("Common_DataUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defeats:.
        /// </summary>
        public static string Common_Defeats {
            get {
                return ResourceManager.GetString("Common_Defeats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defense Points: .
        /// </summary>
        public static string Common_DefensePoints {
            get {
                return ResourceManager.GetString("Common_DefensePoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destroyed: .
        /// </summary>
        public static string Common_Destroyed {
            get {
                return ResourceManager.GetString("Common_Destroyed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detected: .
        /// </summary>
        public static string Common_Detected {
            get {
                return ResourceManager.GetString("Common_Detected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experience.
        /// </summary>
        public static string Common_Experience {
            get {
                return ResourceManager.GetString("Common_Experience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hit Ratio: .
        /// </summary>
        public static string Common_HitRatio {
            get {
                return ResourceManager.GetString("Common_HitRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Experience per Battle: .
        /// </summary>
        public static string Common_MaxExperience {
            get {
                return ResourceManager.GetString("Common_MaxExperience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overall Results.
        /// </summary>
        public static string Common_OverallResults {
            get {
                return ResourceManager.GetString("Common_OverallResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Experience per Battle.
        /// </summary>
        public static string Common_Rating_AvgExperience {
            get {
                return ResourceManager.GetString("Common_Rating_AvgExperience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battles Participated.
        /// </summary>
        public static string Common_Rating_BattlesParticipated {
            get {
                return ResourceManager.GetString("Common_Rating_BattlesParticipated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture Points.
        /// </summary>
        public static string Common_Rating_CapturePoints {
            get {
                return ResourceManager.GetString("Common_Rating_CapturePoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage Caused.
        /// </summary>
        public static string Common_Rating_DamageCaused {
            get {
                return ResourceManager.GetString("Common_Rating_DamageCaused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defense Points.
        /// </summary>
        public static string Common_Rating_DefensePoints {
            get {
                return ResourceManager.GetString("Common_Rating_DefensePoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Rating.
        /// </summary>
        public static string Common_Rating_GlobalRating {
            get {
                return ResourceManager.GetString("Common_Rating_GlobalRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Targets Destroyed.
        /// </summary>
        public static string Common_Rating_TargetsDestroyed {
            get {
                return ResourceManager.GetString("Common_Rating_TargetsDestroyed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Targets Detected.
        /// </summary>
        public static string Common_Rating_TargetsDetected {
            get {
                return ResourceManager.GetString("Common_Rating_TargetsDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Experience.
        /// </summary>
        public static string Common_Rating_TotalExperience {
            get {
                return ResourceManager.GetString("Common_Rating_TotalExperience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Victories.
        /// </summary>
        public static string Common_Rating_Victories {
            get {
                return ResourceManager.GetString("Common_Rating_Victories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Victories/Battles.
        /// </summary>
        public static string Common_Rating_VictoriesBattles {
            get {
                return ResourceManager.GetString("Common_Rating_VictoriesBattles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place.
        /// </summary>
        public static string Common_RatingHeader_Place {
            get {
                return ResourceManager.GetString("Common_RatingHeader_Place", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating.
        /// </summary>
        public static string Common_RatingHeader_Rating {
            get {
                return ResourceManager.GetString("Common_RatingHeader_Rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string Common_RatingHeader_Value {
            get {
                return ResourceManager.GetString("Common_RatingHeader_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered: .
        /// </summary>
        public static string Common_RegisterDate {
            get {
                return ResourceManager.GetString("Common_RegisterDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Experience: .
        /// </summary>
        public static string Common_TotalExperience {
            get {
                return ResourceManager.GetString("Common_TotalExperience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Victories:.
        /// </summary>
        public static string Common_Victories {
            get {
                return ResourceManager.GetString("Common_Victories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap contour {
            get {
                object obj = ResourceManager.GetObject("contour", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        public static string MenuItem_Header_Load {
            get {
                return ResourceManager.GetString("MenuItem_Header_Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string MenuItem_Header_Settings {
            get {
                return ResourceManager.GetString("MenuItem_Header_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Settings_Language {
            get {
                return ResourceManager.GetString("Settings_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player Name.
        /// </summary>
        public static string Settings_PlayerName {
            get {
                return ResourceManager.GetString("Settings_PlayerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Settings_Save {
            get {
                return ResourceManager.GetString("Settings_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battle awards.
        /// </summary>
        public static string Tab_Header_BattleAwards {
            get {
                return ResourceManager.GetString("Tab_Header_BattleAwards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battles.
        /// </summary>
        public static string Tab_Header_Battles {
            get {
                return ResourceManager.GetString("Tab_Header_Battles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charts.
        /// </summary>
        public static string Tab_Header_Chart {
            get {
                return ResourceManager.GetString("Tab_Header_Chart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common.
        /// </summary>
        public static string Tab_Header_Common {
            get {
                return ResourceManager.GetString("Tab_Header_Common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage.
        /// </summary>
        public static string Tab_Header_Damage {
            get {
                return ResourceManager.GetString("Tab_Header_Damage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Epics.
        /// </summary>
        public static string Tab_Header_Epics {
            get {
                return ResourceManager.GetString("Tab_Header_Epics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frag counts.
        /// </summary>
        public static string Tab_Header_FragCounts {
            get {
                return ResourceManager.GetString("Tab_Header_FragCounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frags.
        /// </summary>
        public static string Tab_Header_Frags {
            get {
                return ResourceManager.GetString("Tab_Header_Frags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MasterTanker.
        /// </summary>
        public static string Tab_Header_MasterTanker {
            get {
                return ResourceManager.GetString("Tab_Header_MasterTanker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medals.
        /// </summary>
        public static string Tab_Header_Medals {
            get {
                return ResourceManager.GetString("Tab_Header_Medals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance.
        /// </summary>
        public static string Tab_Header_Performance {
            get {
                return ResourceManager.GetString("Tab_Header_Performance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ratings.
        /// </summary>
        public static string Tab_Header_Ratings {
            get {
                return ResourceManager.GetString("Tab_Header_Ratings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Series.
        /// </summary>
        public static string Tab_Header_Series {
            get {
                return ResourceManager.GetString("Tab_Header_Series", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special awards.
        /// </summary>
        public static string Tab_Header_SpecialAwards {
            get {
                return ResourceManager.GetString("Tab_Header_SpecialAwards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Tab_Header_Time {
            get {
                return ResourceManager.GetString("Tab_Header_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XP.
        /// </summary>
        public static string Tab_Header_XP {
            get {
                return ResourceManager.GetString("Tab_Header_XP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Awarded for individual battles if all of the requirements are met..
        /// </summary>
        public static string Tooltip_BattleHeroAchievements_BattleHero {
            get {
                return ResourceManager.GetString("Tooltip_BattleHeroAchievements_BattleHero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Awarded to a platoon in which all platoon members destroy at least 3 enemy vehicles and survive in battle. Each platoon participant receive this title..
        /// </summary>
        public static string Tooltip_BattleHeroAchievements_BrothersInArms {
            get {
                return ResourceManager.GetString("Tooltip_BattleHeroAchievements_BrothersInArms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hit more enemy vehicles than any other player on your team (at least 6), which are subsequently destroyed by another player.
        ///If two or more players have equal amount of hits, the achievement is granted to the player who has earned more XP for the battle, including additional XP provided to Premium account users. If the amount of XP is equal as well, the achievement is not granted..
        /// </summary>
        public static string Tooltip_BattleHeroAchievements_Confederate {
            get {
                return ResourceManager.GetString("Tooltip_BattleHeroAchievements_Confederate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Awarded to a platoon which destroyed at least 12 enemy vehicles in one battle. Each platoon participant receive this title..
        /// </summary>
        public static string Tooltip_BattleHeroAchievements_CrucialContribution {
            get {
                return ResourceManager.GetString("Tooltip_BattleHeroAchievements_CrucialContribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reduce the amount of enemy capture points on a friendly base by 70 or more.
        ///If two or more players have reduced equal amount of capture points, the achievement is granted to the player who has earned more XP in the battle (including additional XP provided to Premium account users). If the amount of XP is equal as well, the achievement is not awarded..
        /// </summary>
        public static string Tooltip_BattleHeroAchievements_Defender {
            get {
                return ResourceManager.GetString("Tooltip_BattleHeroAchievements_Defender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture the maximum number of points from the enemy base, but not less than 80.
        ///The achievement is granted on successful base capture, including only the points that were part of the base capture. If the battle ends in a draw, the achievement is granted to the first player to receive 80 or more capture points..
        /// </summary>
        public static string Tooltip_BattleHeroAchievements_Invader {
            get {
                return ResourceManager.GetString("Tooltip_BattleHeroAchievements_Invader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Awarded to the player who helps the team damage at least six enemy vehicles by highlighting them. The tanks must be highlighted only by you when they take damage..
        /// </summary>
        public static string Tooltip_BattleHeroAchievements_PatrolDuty {
            get {
                return ResourceManager.GetString("Tooltip_BattleHeroAchievements_PatrolDuty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detect most enemy tanks and self-propelled guns than anyone else on your team (at least nine). The achievement is granted to the winning team only.
        ///If two or more players have detected equal number of enemy vehicles, the achievement is granted to the player who has earned more XP, including additional XP provided to Premium account users. If the amount of XP is equal as well, the achievement is not granted..
        /// </summary>
        public static string Tooltip_BattleHeroAchievements_Scout {
            get {
                return ResourceManager.GetString("Tooltip_BattleHeroAchievements_Scout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Achieve at least 85% hits out of a minimum of ten shots fired with the potential damage of 1,000 HP and more. Non-penetrating hits are included, but hits on friendly units are not included.
        ///If two or more players have an equal hit ratio, the achievement is granted to the player with the highest potential damage. If two or more players have an equal amount of potential damage, the achievement is granted to the player who earned more XP for the battle, including additional XP provided to Premium Account user [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Tooltip_BattleHeroAchievements_Sniper {
            get {
                return ResourceManager.GetString("Tooltip_BattleHeroAchievements_Sniper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive the most hits (at least 11) of any player on your team, with potential damage of at least 1,000 HP, and survive.
        ///If two or more players have equal amount of hits, the achievement is granted to the player with the highest potential damage. If two or more players have equal amount of potential damage, the achievement is granted to the player who has earned more XP, including additional XP provided to Premium account users. If the amount of XP is equal as well, the achievement is not granted..
        /// </summary>
        public static string Tooltip_BattleHeroAchievements_SteelWall {
            get {
                return ResourceManager.GetString("Tooltip_BattleHeroAchievements_SteelWall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destroy more enemy vehicles than any other player in your team during the battle (at least 6).
        ///If two or more players have destroyed equal amount vehicles, the achievement is granted to the player who has earned more XP for the battle, including additional XP provided to Premium account users. If the amount of XP is equal as well, the achievement is not granted..
        /// </summary>
        public static string Tooltip_BattleHeroAchievements_Warrior {
            get {
                return ResourceManager.GetString("Tooltip_BattleHeroAchievements_Warrior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earn more experience in a single battle than the average highest experience of 50% of all players in the same tank within the last seven days..
        /// </summary>
        public static string Tooltip_MarkOfMastery_1 {
            get {
                return ResourceManager.GetString("Tooltip_MarkOfMastery_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earn more experience in a single battle than the average highest experience of 80% of all players in the same tank within the last seven days..
        /// </summary>
        public static string Tooltip_MarkOfMastery_2 {
            get {
                return ResourceManager.GetString("Tooltip_MarkOfMastery_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earn more experience in a single battle than the average highest experience of 95% of all players in the same tank within the last seven days..
        /// </summary>
        public static string Tooltip_MarkOfMastery_3 {
            get {
                return ResourceManager.GetString("Tooltip_MarkOfMastery_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earn more experience in a single battle than the average highest experience of 99% of all players in the same tank within the last seven days..
        /// </summary>
        public static string Tooltip_MarkOfMastery_4 {
            get {
                return ResourceManager.GetString("Tooltip_MarkOfMastery_4", resourceCulture);
            }
        }
    }
}
