//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WotDossier.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Tanks {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Tanks() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WotDossier.Resources.Tanks", typeof(Tanks).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IS.
        /// </summary>
        public static string _is {
            get {
                return ResourceManager.GetString("is", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A-20.
        /// </summary>
        public static string a_20 {
            get {
                return ResourceManager.GetString("a_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A-32.
        /// </summary>
        public static string a_32 {
            get {
                return ResourceManager.GetString("a_32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A-43.
        /// </summary>
        public static string a43 {
            get {
                return ResourceManager.GetString("a43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A-44.
        /// </summary>
        public static string a44 {
            get {
                return ResourceManager.GetString("a44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AT-1.
        /// </summary>
        public static string at_1 {
            get {
                return ResourceManager.GetString("at_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BT-2.
        /// </summary>
        public static string bt_2 {
            get {
                return ResourceManager.GetString("bt_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BT-7.
        /// </summary>
        public static string bt_7 {
            get {
                return ResourceManager.GetString("bt_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BT-SV.
        /// </summary>
        public static string bt_sv {
            get {
                return ResourceManager.GetString("bt_sv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Churchill III.
        /// </summary>
        public static string churchill_ll {
            get {
                return ResourceManager.GetString("churchill_ll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GAZ-74b.
        /// </summary>
        public static string gaz_74b {
            get {
                return ResourceManager.GetString("gaz_74b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IS-7.
        /// </summary>
        public static string is_7 {
            get {
                return ResourceManager.GetString("is_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (R) IS-7.
        /// </summary>
        public static string is_7_fallout {
            get {
                return ResourceManager.GetString("is_7_fallout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IS-7.
        /// </summary>
        public static string is_7_igr {
            get {
                return ResourceManager.GetString("is_7_igr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISU-152.
        /// </summary>
        public static string isu_152 {
            get {
                return ResourceManager.GetString("isu_152", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISU-152.
        /// </summary>
        public static string isu_152_igr {
            get {
                return ResourceManager.GetString("isu_152_igr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KV.
        /// </summary>
        public static string kv {
            get {
                return ResourceManager.GetString("kv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KV-13.
        /// </summary>
        public static string kv_13 {
            get {
                return ResourceManager.GetString("kv_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KV-1S.
        /// </summary>
        public static string kv_1s {
            get {
                return ResourceManager.GetString("kv_1s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KV-3.
        /// </summary>
        public static string kv_3 {
            get {
                return ResourceManager.GetString("kv_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KV-5.
        /// </summary>
        public static string kv_5 {
            get {
                return ResourceManager.GetString("kv_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KV-5.
        /// </summary>
        public static string kv_5_igr {
            get {
                return ResourceManager.GetString("kv_5_igr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KV-2.
        /// </summary>
        public static string kv2 {
            get {
                return ResourceManager.GetString("kv2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KV-2.
        /// </summary>
        public static string kv2_igr {
            get {
                return ResourceManager.GetString("kv2_igr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KV-4.
        /// </summary>
        public static string kv4 {
            get {
                return ResourceManager.GetString("kv4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LTP.
        /// </summary>
        public static string ltp {
            get {
                return ResourceManager.GetString("ltp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M3 Light.
        /// </summary>
        public static string m3_stuart_ll {
            get {
                return ResourceManager.GetString("m3_stuart_ll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matilda IV.
        /// </summary>
        public static string matilda_ii_ll {
            get {
                return ResourceManager.GetString("matilda_ii_ll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MS-1.
        /// </summary>
        public static string ms_1 {
            get {
                return ResourceManager.GetString("ms_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MS-1.
        /// </summary>
        public static string ms_1_bot {
            get {
                return ResourceManager.GetString("ms_1_bot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MT-25.
        /// </summary>
        public static string mt25 {
            get {
                return ResourceManager.GetString("mt25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object 140.
        /// </summary>
        public static string object_140 {
            get {
                return ResourceManager.GetString("object_140", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object 261.
        /// </summary>
        public static string object_261 {
            get {
                return ResourceManager.GetString("object_261", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object 430.
        /// </summary>
        public static string object_430 {
            get {
                return ResourceManager.GetString("object_430", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object 907.
        /// </summary>
        public static string object_907 {
            get {
                return ResourceManager.GetString("object_907", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object 907A.
        /// </summary>
        public static string object_907a {
            get {
                return ResourceManager.GetString("object_907a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IS-6.
        /// </summary>
        public static string object252 {
            get {
                return ResourceManager.GetString("object252", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object 263.
        /// </summary>
        public static string object263 {
            get {
                return ResourceManager.GetString("object263", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object 268.
        /// </summary>
        public static string object268 {
            get {
                return ResourceManager.GetString("object268", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object 416.
        /// </summary>
        public static string object416 {
            get {
                return ResourceManager.GetString("object416", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spectator.
        /// </summary>
        public static string observer {
            get {
                return ResourceManager.GetString("observer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SU-85.
        /// </summary>
        public static string r02_su_85 {
            get {
                return ResourceManager.GetString("r02_su_85", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T-34.
        /// </summary>
        public static string r04_t_34 {
            get {
                return ResourceManager.GetString("r04_t_34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T-28.
        /// </summary>
        public static string r06_t_28 {
            get {
                return ResourceManager.GetString("r06_t_28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SU-122A.
        /// </summary>
        public static string r100_su122a {
            get {
                return ResourceManager.GetString("r100_su122a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object 430 Version II.
        /// </summary>
        public static string r104_object_430_ii {
            get {
                return ResourceManager.GetString("r104_object_430_ii", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BT-7 artillery.
        /// </summary>
        public static string r105_bt_7a {
            get {
                return ResourceManager.GetString("r105_bt_7a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KV-85.
        /// </summary>
        public static string r106_kv85 {
            get {
                return ResourceManager.GetString("r106_kv85", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KV-85.
        /// </summary>
        public static string r106_kv85_igr {
            get {
                return ResourceManager.GetString("r106_kv85_igr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LTTB.
        /// </summary>
        public static string r107_ltb {
            get {
                return ResourceManager.GetString("r107_ltb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T-34-85M.
        /// </summary>
        public static string r108_t34_85m {
            get {
                return ResourceManager.GetString("r108_t34_85m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T-54 ltwt..
        /// </summary>
        public static string r109_t54s {
            get {
                return ResourceManager.GetString("r109_t54s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object 260.
        /// </summary>
        public static string r110_object_260 {
            get {
                return ResourceManager.GetString("r110_object_260", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISU-130.
        /// </summary>
        public static string r111_isu130 {
            get {
                return ResourceManager.GetString("r111_isu130", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T-54 first prototype.
        /// </summary>
        public static string r112_t54_45 {
            get {
                return ResourceManager.GetString("r112_t54_45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IS-5 (Object 730).
        /// </summary>
        public static string r113_object_730 {
            get {
                return ResourceManager.GetString("r113_object_730", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object 244.
        /// </summary>
        public static string r114_object_244 {
            get {
                return ResourceManager.GetString("r114_object_244", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IS-3 auto.
        /// </summary>
        public static string r115_is_3_auto {
            get {
                return ResourceManager.GetString("r115_is_3_auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISU-122S.
        /// </summary>
        public static string r116_isu122c_berlin {
            get {
                return ResourceManager.GetString("r116_isu122c_berlin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T-34-85 Rudy.
        /// </summary>
        public static string r117_t34_85_rudy {
            get {
                return ResourceManager.GetString("r117_t34_85_rudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T-28E with F-30.
        /// </summary>
        public static string r118_t28_f30 {
            get {
                return ResourceManager.GetString("r118_t28_f30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object 777 Version II.
        /// </summary>
        public static string r119_object_777 {
            get {
                return ResourceManager.GetString("r119_object_777", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T-22 medium.
        /// </summary>
        public static string r120_t22sr_a22 {
            get {
                return ResourceManager.GetString("r120_t22sr_a22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KV-4 KTTS.
        /// </summary>
        public static string r121_kv4_ktt {
            get {
                return ResourceManager.GetString("r121_kv4_ktt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T-44-100.
        /// </summary>
        public static string r122_t44_100 {
            get {
                return ResourceManager.GetString("r122_t44_100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IS-3.
        /// </summary>
        public static string r19_is_3 {
            get {
                return ResourceManager.GetString("r19_is_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IS-3.
        /// </summary>
        public static string r19_is_3_igr {
            get {
                return ResourceManager.GetString("r19_is_3_igr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SU-76M.
        /// </summary>
        public static string r24_su_76 {
            get {
                return ResourceManager.GetString("r24_su_76", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KV-220-2 Beta Test.
        /// </summary>
        public static string r38_kv_220 {
            get {
                return ResourceManager.GetString("r38_kv_220", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KV-220-2.
        /// </summary>
        public static string r38_kv_220_action {
            get {
                return ResourceManager.GetString("r38_kv_220_action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 212A.
        /// </summary>
        public static string r51_object_212 {
            get {
                return ResourceManager.GetString("r51_object_212", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object 704.
        /// </summary>
        public static string r53_object_704 {
            get {
                return ResourceManager.GetString("r53_object_704", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IS-2.
        /// </summary>
        public static string r71_is_2b {
            get {
                return ResourceManager.GetString("r71_is_2b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KV-1.
        /// </summary>
        public static string r80_kv1 {
            get {
                return ResourceManager.GetString("r80_kv1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T-10.
        /// </summary>
        public static string r81_is8 {
            get {
                return ResourceManager.GetString("r81_is8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T-62A.
        /// </summary>
        public static string r87_t62a {
            get {
                return ResourceManager.GetString("r87_t62a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (R) T-62A.
        /// </summary>
        public static string r87_t62a_fallout {
            get {
                return ResourceManager.GetString("r87_t62a_fallout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IS-4.
        /// </summary>
        public static string r90_is_4m {
            get {
                return ResourceManager.GetString("r90_is_4m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S-51.
        /// </summary>
        public static string s_51 {
            get {
                return ResourceManager.GetString("s_51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ST-I.
        /// </summary>
        public static string st_i {
            get {
                return ResourceManager.GetString("st_i", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SU-100.
        /// </summary>
        public static string su_100 {
            get {
                return ResourceManager.GetString("su_100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SU-101.
        /// </summary>
        public static string su_101 {
            get {
                return ResourceManager.GetString("su_101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SU-14-2.
        /// </summary>
        public static string su_14 {
            get {
                return ResourceManager.GetString("su_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SU-152.
        /// </summary>
        public static string su_152 {
            get {
                return ResourceManager.GetString("su_152", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SU-152.
        /// </summary>
        public static string su_152_igr {
            get {
                return ResourceManager.GetString("su_152_igr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SU-18.
        /// </summary>
        public static string su_18 {
            get {
                return ResourceManager.GetString("su_18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SU-26.
        /// </summary>
        public static string su_26 {
            get {
                return ResourceManager.GetString("su_26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SU-5.
        /// </summary>
        public static string su_5 {
            get {
                return ResourceManager.GetString("su_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SU-8.
        /// </summary>
        public static string su_8 {
            get {
                return ResourceManager.GetString("su_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SU-85I.
        /// </summary>
        public static string su_85i {
            get {
                return ResourceManager.GetString("su_85i", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SU-100M1.
        /// </summary>
        public static string su100m1 {
            get {
                return ResourceManager.GetString("su100m1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SU-100Y.
        /// </summary>
        public static string su100y {
            get {
                return ResourceManager.GetString("su100y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SU-122-44.
        /// </summary>
        public static string su122_44 {
            get {
                return ResourceManager.GetString("su122_44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SU-122-54.
        /// </summary>
        public static string su122_54 {
            get {
                return ResourceManager.GetString("su122_54", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SU-14-1.
        /// </summary>
        public static string su14_1 {
            get {
                return ResourceManager.GetString("su14_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SU-76I.
        /// </summary>
        public static string su76i {
            get {
                return ResourceManager.GetString("su76i", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T-127.
        /// </summary>
        public static string t_127 {
            get {
                return ResourceManager.GetString("t_127", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T-26.
        /// </summary>
        public static string t_26 {
            get {
                return ResourceManager.GetString("t_26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T-26.
        /// </summary>
        public static string t_26_bot {
            get {
                return ResourceManager.GetString("t_26_bot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T-34-85.
        /// </summary>
        public static string t_34_85 {
            get {
                return ResourceManager.GetString("t_34_85", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T-34-85.
        /// </summary>
        public static string t_34_85_training {
            get {
                return ResourceManager.GetString("t_34_85_training", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T-43.
        /// </summary>
        public static string t_43 {
            get {
                return ResourceManager.GetString("t_43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T-44.
        /// </summary>
        public static string t_44 {
            get {
                return ResourceManager.GetString("t_44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T-44.
        /// </summary>
        public static string t_44_igr {
            get {
                return ResourceManager.GetString("t_44_igr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T-46.
        /// </summary>
        public static string t_46 {
            get {
                return ResourceManager.GetString("t_46", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T-50.
        /// </summary>
        public static string t_50 {
            get {
                return ResourceManager.GetString("t_50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T-50-2.
        /// </summary>
        public static string t_50_2 {
            get {
                return ResourceManager.GetString("t_50_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T-54.
        /// </summary>
        public static string t_54 {
            get {
                return ResourceManager.GetString("t_54", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T-60.
        /// </summary>
        public static string t_60 {
            get {
                return ResourceManager.GetString("t_60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T-70.
        /// </summary>
        public static string t_70 {
            get {
                return ResourceManager.GetString("t_70", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T-150.
        /// </summary>
        public static string t150 {
            get {
                return ResourceManager.GetString("t150", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T-44-122.
        /// </summary>
        public static string t44_122 {
            get {
                return ResourceManager.GetString("t44_122", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T-44-85.
        /// </summary>
        public static string t44_85 {
            get {
                return ResourceManager.GetString("t44_85", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T-80.
        /// </summary>
        public static string t80 {
            get {
                return ResourceManager.GetString("t80", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tetrarch.
        /// </summary>
        public static string tetrarch_ll {
            get {
                return ResourceManager.GetString("tetrarch_ll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valentine II.
        /// </summary>
        public static string valentine_ll {
            get {
                return ResourceManager.GetString("valentine_ll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valentine II.
        /// </summary>
        public static string valentine_ll_igr {
            get {
                return ResourceManager.GetString("valentine_ll_igr", resourceCulture);
            }
        }
    }
}
