namespace WotDossier.Domain.Server
{
    public class MedalAchievements
    {
        public int medalDumitru;
        public int invader;
        public int medalLehvaslaiho;
        public int warrior;
        public int medalHalonen;
        public int medalPascucci;
        public int medalOrlik;
        public int medalBrothersInArms;
        public int mousebane;
        public int tank_expert_france;
        public int mechanic_engineer_ussr;
        public int medalBrunoPietro;
        public int medalDeLanglade;
        public int luckyDevil;
        public int defender;
        public int armorPiercer;
        public int medal_kay;
        public int supporter;
        public int mechanic_engineer;
        public int steelwall;
        public int medalKnispel;
        public int medalBoelter;
        public int medalEkins;
        public int heroesOfRassenay;
        public int medalTamadaYoshio;
        public int tank_expert_usa;
        public int mechanic_engineer_germany;
        public int tank_expert;
        public int ironMan;
        public int medalRadleyWalters;
        public int kamikaze;
        public int tank_expert_germany;
        public int beasthunter;
        public int sniper;
        public int medalTarczay;
        public int medalLavrinenko;
        public int mechanic_engineer_france;
        public int medalOskin;
        public int medalBurda;
        public int medalBillotte;
        public int huntsman;
        public int handOfDeath;
        public int medalFadin;
        public int medalLafayettePool;
        public int tank_expert_china;
        public int mechanic_engineer_usa;
        public int medalKolobanov;
        public int pattonValley;
        public int bombardier;
        public int medalAbrams;
        public int medalPoppel;
        public int medalCrucialContribution;
        public int raider;
        public int mechanic_engineer_uk;
        public int invincible;
        public int lumberjack;
        public int sturdy;
        public int titleSniper;
        public int sinai;
        public int diehard;
        public int medalCarius;
        public int medalLeClerc;
        public int tank_expert_ussr;
        public int evileye;
        public int mechanic_engineer_china;
        public int medalNikolas;
        public int scout;
        //added in 0.8.11
        public int sniper2;
        public int main_gun;
        //added in 0.9.1
        public int marksOnGun;
        public int movingAvgDamage;
        public int medalMonolith;
        public int medalAntiSpgFire;
        public int medalGore;
        public int medalCoolBlood;
        public int medalStark;
    }
}