//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WotDossier.Dal.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WotDossier.Dal.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training area.
        /// </summary>
        internal static string Map_00_tank_tutorial {
            get {
                return ResourceManager.GetString("Map_00_tank_tutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Karelia.
        /// </summary>
        internal static string Map_01_karelia {
            get {
                return ResourceManager.GetString("Map_01_karelia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malinovka.
        /// </summary>
        internal static string Map_02_malinovka {
            get {
                return ResourceManager.GetString("Map_02_malinovka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Province.
        /// </summary>
        internal static string Map_03_campania {
            get {
                return ResourceManager.GetString("Map_03_campania", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Himmelsdorf.
        /// </summary>
        internal static string Map_04_himmelsdorf {
            get {
                return ResourceManager.GetString("Map_04_himmelsdorf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prokhorovka.
        /// </summary>
        internal static string Map_05_prohorovka {
            get {
                return ResourceManager.GetString("Map_05_prohorovka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ensk.
        /// </summary>
        internal static string Map_06_ensk {
            get {
                return ResourceManager.GetString("Map_06_ensk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lakeville.
        /// </summary>
        internal static string Map_07_lakeville {
            get {
                return ResourceManager.GetString("Map_07_lakeville", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ruinberg.
        /// </summary>
        internal static string Map_08_ruinberg {
            get {
                return ResourceManager.GetString("Map_08_ruinberg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mines.
        /// </summary>
        internal static string Map_10_hills {
            get {
                return ResourceManager.GetString("Map_10_hills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Murovanka.
        /// </summary>
        internal static string Map_11_murovanka {
            get {
                return ResourceManager.GetString("Map_11_murovanka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erlenberg.
        /// </summary>
        internal static string Map_13_erlenberg {
            get {
                return ResourceManager.GetString("Map_13_erlenberg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siegfried Line.
        /// </summary>
        internal static string Map_14_siegfried_line {
            get {
                return ResourceManager.GetString("Map_14_siegfried_line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Komarin.
        /// </summary>
        internal static string Map_15_komarin {
            get {
                return ResourceManager.GetString("Map_15_komarin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Widepark.
        /// </summary>
        internal static string Map_17_munchen {
            get {
                return ResourceManager.GetString("Map_17_munchen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliff.
        /// </summary>
        internal static string Map_18_cliff {
            get {
                return ResourceManager.GetString("Map_18_cliff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abbey.
        /// </summary>
        internal static string Map_19_monastery {
            get {
                return ResourceManager.GetString("Map_19_monastery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swamp.
        /// </summary>
        internal static string Map_22_slough {
            get {
                return ResourceManager.GetString("Map_22_slough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Westfield.
        /// </summary>
        internal static string Map_23_westfeld {
            get {
                return ResourceManager.GetString("Map_23_westfeld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sand River.
        /// </summary>
        internal static string Map_28_desert {
            get {
                return ResourceManager.GetString("Map_28_desert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Halluf.
        /// </summary>
        internal static string Map_29_el_hallouf {
            get {
                return ResourceManager.GetString("Map_29_el_hallouf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Airfield.
        /// </summary>
        internal static string Map_31_airfield {
            get {
                return ResourceManager.GetString("Map_31_airfield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fjords.
        /// </summary>
        internal static string Map_33_fjord {
            get {
                return ResourceManager.GetString("Map_33_fjord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redshire.
        /// </summary>
        internal static string Map_34_redshire {
            get {
                return ResourceManager.GetString("Map_34_redshire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steppes.
        /// </summary>
        internal static string Map_35_steppes {
            get {
                return ResourceManager.GetString("Map_35_steppes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fisherman&apos;s Bay.
        /// </summary>
        internal static string Map_36_fishing_bay {
            get {
                return ResourceManager.GetString("Map_36_fishing_bay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mountain Pass.
        /// </summary>
        internal static string Map_37_caucasus {
            get {
                return ResourceManager.GetString("Map_37_caucasus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arctic Region.
        /// </summary>
        internal static string Map_38_mannerheim_line {
            get {
                return ResourceManager.GetString("Map_38_mannerheim_line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to South Coast.
        /// </summary>
        internal static string Map_39_crimea {
            get {
                return ResourceManager.GetString("Map_39_crimea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        internal static string Map_42_north_america {
            get {
                return ResourceManager.GetString("Map_42_north_america", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Northwest.
        /// </summary>
        internal static string Map_43_north_america {
            get {
                return ResourceManager.GetString("Map_43_north_america", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live Oaks.
        /// </summary>
        internal static string Map_44_north_america {
            get {
                return ResourceManager.GetString("Map_44_north_america", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highway.
        /// </summary>
        internal static string Map_45_north_america {
            get {
                return ResourceManager.GetString("Map_45_north_america", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serene Coast.
        /// </summary>
        internal static string Map_47_canada_a {
            get {
                return ResourceManager.GetString("Map_47_canada_a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dragon Ridge.
        /// </summary>
        internal static string Map_51_asia {
            get {
                return ResourceManager.GetString("Map_51_asia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hidden Village.
        /// </summary>
        internal static string Map_53_japan {
            get {
                return ResourceManager.GetString("Map_53_japan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pearl River.
        /// </summary>
        internal static string Map_60_asia_miao {
            get {
                return ResourceManager.GetString("Map_60_asia_miao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tundra.
        /// </summary>
        internal static string Map_63_tundra {
            get {
                return ResourceManager.GetString("Map_63_tundra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sacred Valley.
        /// </summary>
        internal static string Map_73_asia_korea {
            get {
                return ResourceManager.GetString("Map_73_asia_korea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windstorm.
        /// </summary>
        internal static string Map_84_winter {
            get {
                return ResourceManager.GetString("Map_84_winter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Severogorsk.
        /// </summary>
        internal static string Map_85_winter {
            get {
                return ResourceManager.GetString("Map_85_winter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Winter Himmelsdorf.
        /// </summary>
        internal static string Map_86_himmelsdorf_winter {
            get {
                return ResourceManager.GetString("Map_86_himmelsdorf_winter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ruinberg on Fire.
        /// </summary>
        internal static string Map_87_ruinberg_on_fire {
            get {
                return ResourceManager.GetString("Map_87_ruinberg_on_fire", resourceCulture);
            }
        }
    }
}
