//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WotDossier.Applications.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WotDossier.Applications.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historical Battle.
        /// </summary>
        internal static string BattleMode_HistoricalBattle {
            get {
                return ResourceManager.GetString("BattleMode_HistoricalBattle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random, Company.
        /// </summary>
        internal static string BattleMode_RandomCompany {
            get {
                return ResourceManager.GetString("BattleMode_RandomCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team Battle.
        /// </summary>
        internal static string BattleMode_TeamBattle {
            get {
                return ResourceManager.GetString("BattleMode_TeamBattle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defeat.
        /// </summary>
        internal static string BattleStatus_Defeat {
            get {
                return ResourceManager.GetString("BattleStatus_Defeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw.
        /// </summary>
        internal static string BattleStatus_Draw {
            get {
                return ResourceManager.GetString("BattleStatus_Draw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Data.
        /// </summary>
        internal static string BattleStatus_Unknown {
            get {
                return ResourceManager.GetString("BattleStatus_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Victory.
        /// </summary>
        internal static string BattleStatus_Victory {
            get {
                return ResourceManager.GetString("BattleStatus_Victory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clan War.
        /// </summary>
        internal static string BattleType_ClanWar {
            get {
                return ResourceManager.GetString("BattleType_ClanWar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company War.
        /// </summary>
        internal static string BattleType_CompanyWar {
            get {
                return ResourceManager.GetString("BattleType_CompanyWar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cyber Sport.
        /// </summary>
        internal static string BattleType_CyberSport {
            get {
                return ResourceManager.GetString("BattleType_CyberSport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historical battle.
        /// </summary>
        internal static string BattleType_Historical {
            get {
                return ResourceManager.GetString("BattleType_Historical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular.
        /// </summary>
        internal static string BattleType_Regular {
            get {
                return ResourceManager.GetString("BattleType_Regular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tournament.
        /// </summary>
        internal static string BattleType_Tournament {
            get {
                return ResourceManager.GetString("BattleType_Tournament", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training.
        /// </summary>
        internal static string BattleType_Training {
            get {
                return ResourceManager.GetString("BattleType_Training", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutorial.
        /// </summary>
        internal static string BattleType_Tutorial {
            get {
                return ResourceManager.GetString("BattleType_Tutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battles: {0}
        ///Avg Spotted: {1:0.00}.
        /// </summary>
        internal static string Chart_Tooltip_AvgSpotted {
            get {
                return ResourceManager.GetString("Chart_Tooltip_AvgSpotted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battles: {0}
        ///Avg XP: {1:0.00}.
        /// </summary>
        internal static string Chart_Tooltip_AvgXp {
            get {
                return ResourceManager.GetString("Chart_Tooltip_AvgXp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battles: {0}
        ///Ratio: {1:0.00}.
        /// </summary>
        internal static string Chart_Tooltip_KillDeathRatio {
            get {
                return ResourceManager.GetString("Chart_Tooltip_KillDeathRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battles: {0}
        ///Survive %: {1:0.00}.
        /// </summary>
        internal static string Chart_Tooltip_Survive {
            get {
                return ResourceManager.GetString("Chart_Tooltip_Survive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avg damage.
        /// </summary>
        internal static string ChartLegend_AvgDamage {
            get {
                return ResourceManager.GetString("ChartLegend_AvgDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effectivity Rating.
        /// </summary>
        internal static string ChartLegend_ER {
            get {
                return ResourceManager.GetString("ChartLegend_ER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Win %.
        /// </summary>
        internal static string ChartLegend_WinPercent {
            get {
                return ResourceManager.GetString("ChartLegend_WinPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WN6.
        /// </summary>
        internal static string ChartLegend_WN6Rating {
            get {
                return ResourceManager.GetString("ChartLegend_WN6Rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battles: {0}
        ///Avg Damage: {1:0.00}.
        /// </summary>
        internal static string ChartTooltipFormat_AvgDamage {
            get {
                return ResourceManager.GetString("ChartTooltipFormat_AvgDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battles: {0}
        ///Rating: {1:0.00}.
        /// </summary>
        internal static string ChartTooltipFormat_Rating {
            get {
                return ResourceManager.GetString("ChartTooltipFormat_Rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battles: {0}
        ///Win percent: {1:0.00}.
        /// </summary>
        internal static string ChartTooltipFormat_WinPercent {
            get {
                return ResourceManager.GetString("ChartTooltipFormat_WinPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credits.
        /// </summary>
        internal static string Column_Replay_Credits {
            get {
                return ResourceManager.GetString("Column_Replay_Credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damaged.
        /// </summary>
        internal static string Column_Replay_Damaged {
            get {
                return ResourceManager.GetString("Column_Replay_Damaged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage Dealt.
        /// </summary>
        internal static string Column_Replay_DamageDealt {
            get {
                return ResourceManager.GetString("Column_Replay_DamageDealt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frags.
        /// </summary>
        internal static string Column_Replay_Frags {
            get {
                return ResourceManager.GetString("Column_Replay_Frags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XP.
        /// </summary>
        internal static string Column_Replay_XP {
            get {
                return ResourceManager.GetString("Column_Replay_XP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error on file deletion, please check your access rights({0}).
        /// </summary>
        internal static string ErrorMsg_ErrorOnFileDeletion {
            get {
                return ResourceManager.GetString("ErrorMsg_ErrorOnFileDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error on file deletion, please check your access rights.
        /// </summary>
        internal static string ErrorMsg_ErrorOnFilesDeletion {
            get {
                return ResourceManager.GetString("ErrorMsg_ErrorOnFilesDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error on getting player data from server.
        /// </summary>
        internal static string ErrorMsg_GetPlayerData {
            get {
                return ResourceManager.GetString("ErrorMsg_GetPlayerData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t get player info from server.
        /// </summary>
        internal static string ErrorMsg_GetPlayerInfo {
            get {
                return ResourceManager.GetString("ErrorMsg_GetPlayerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m&apos; m &apos;s&apos; s&apos;.
        /// </summary>
        internal static string ExtendedTimeFormat {
            get {
                return ResourceManager.GetString("ExtendedTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experience.
        /// </summary>
        internal static string Label_Experience {
            get {
                return ResourceManager.GetString("Label_Experience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assault.
        /// </summary>
        internal static string Label_Replay_MapMode_Assault {
            get {
                return ResourceManager.GetString("Label_Replay_MapMode_Assault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domination.
        /// </summary>
        internal static string Label_Replay_MapMode_domination {
            get {
                return ResourceManager.GetString("Label_Replay_MapMode_domination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standart.
        /// </summary>
        internal static string Label_Replay_MapMode_Standart {
            get {
                return ResourceManager.GetString("Label_Replay_MapMode_Standart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experience (x{0} for the first win in a day).
        /// </summary>
        internal static string Label_Replay_XpFactorFormat {
            get {
                return ResourceManager.GetString("Label_Replay_XpFactorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string Language_English {
            get {
                return ResourceManager.GetString("Language_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Русский.
        /// </summary>
        internal static string Language_Russian {
            get {
                return ResourceManager.GetString("Language_Russian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t find player data - {0}.
        /// </summary>
        internal static string Msg_CantFindPlayerData {
            get {
                return ResourceManager.GetString("Msg_CantFindPlayerData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t find replays directory - &apos;{0}&apos;..
        /// </summary>
        internal static string Msg_CantFindReplaysDirectory {
            get {
                return ResourceManager.GetString("Msg_CantFindReplaysDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t get clan data from server.
        /// </summary>
        internal static string Msg_CantGetClanDataFromServer {
            get {
                return ResourceManager.GetString("Msg_CantGetClanDataFromServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error on replay file read.
        /// </summary>
        internal static string Msg_Error_on_replay_file_read {
            get {
                return ResourceManager.GetString("Msg_Error_on_replay_file_read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error on data load.
        /// </summary>
        internal static string Msg_ErrorOnDataLoad {
            get {
                return ResourceManager.GetString("Msg_ErrorOnDataLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error on play replay.
        /// </summary>
        internal static string Msg_ErrorOnPlayReplay {
            get {
                return ResourceManager.GetString("Msg_ErrorOnPlayReplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t load replay file. File incomplete or not supported.
        /// </summary>
        internal static string Msg_File_incomplete_or_not_supported {
            get {
                return ResourceManager.GetString("Msg_File_incomplete_or_not_supported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version available - {0}. Do you want download it now?.
        /// </summary>
        internal static string Msg_NewVersion {
            get {
                return ResourceManager.GetString("Msg_NewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete files and save battle results to local base? Press Yes to save results? Press No to complete deletion..
        /// </summary>
        internal static string Msg_ReplaysDelete {
            get {
                return ResourceManager.GetString("Msg_ReplaysDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently you not logined to the target site. You need to be already authentificated in IE. Do you want to open the site in browser?.
        /// </summary>
        internal static string Msg_ReplayUpload_AuthentificationFailure {
            get {
                return ResourceManager.GetString("Msg_ReplayUpload_AuthentificationFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server not selected.
        /// </summary>
        internal static string Msg_ServerNotSelected {
            get {
                return ResourceManager.GetString("Msg_ServerNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing file {0}/{1} - {2}....
        /// </summary>
        internal static string ProgressLabel_Processing_file_format {
            get {
                return ResourceManager.GetString("ProgressLabel_Processing_file_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading replays.
        /// </summary>
        internal static string ProgressTitle_Loading_replays {
            get {
                return ResourceManager.GetString("ProgressTitle_Loading_replays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commander.
        /// </summary>
        internal static string Role_commander {
            get {
                return ResourceManager.GetString("Role_commander", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diplomat.
        /// </summary>
        internal static string Role_diplomat {
            get {
                return ResourceManager.GetString("Role_diplomat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leader.
        /// </summary>
        internal static string Role_leader {
            get {
                return ResourceManager.GetString("Role_leader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private.
        /// </summary>
        internal static string Role_private {
            get {
                return ResourceManager.GetString("Role_private", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recruit.
        /// </summary>
        internal static string Role_recruit {
            get {
                return ResourceManager.GetString("Role_recruit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recruiter.
        /// </summary>
        internal static string Role_recruiter {
            get {
                return ResourceManager.GetString("Role_recruiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treasurer.
        /// </summary>
        internal static string Role_treasurer {
            get {
                return ResourceManager.GetString("Role_treasurer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vice Leader.
        /// </summary>
        internal static string Role_vice_leader {
            get {
                return ResourceManager.GetString("Role_vice_leader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All observation period.
        /// </summary>
        internal static string StatisticPeriod_AllObservationPeriod {
            get {
                return ResourceManager.GetString("StatisticPeriod_AllObservationPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results from {0}.
        /// </summary>
        internal static string StatisticPeriod_Custom {
            get {
                return ResourceManager.GetString("StatisticPeriod_Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        internal static string StatisticPeriod_Custom_ComboItem {
            get {
                return ResourceManager.GetString("StatisticPeriod_Custom_ComboItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last {0} Battles results.
        /// </summary>
        internal static string StatisticPeriod_LastNBattles {
            get {
                return ResourceManager.GetString("StatisticPeriod_LastNBattles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last N Battles.
        /// </summary>
        internal static string StatisticPeriod_LastNBattles_ComboItem {
            get {
                return ResourceManager.GetString("StatisticPeriod_LastNBattles_ComboItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last week.
        /// </summary>
        internal static string StatisticPeriod_LastWeek {
            get {
                return ResourceManager.GetString("StatisticPeriod_LastWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent.
        /// </summary>
        internal static string StatisticPeriod_Recent {
            get {
                return ResourceManager.GetString("StatisticPeriod_Recent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All captured results.
        /// </summary>
        internal static string TabHeader_AllObservationPeriod {
            get {
                return ResourceManager.GetString("TabHeader_AllObservationPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results from {0}.
        /// </summary>
        internal static string TabHeader_Custom {
            get {
                return ResourceManager.GetString("TabHeader_Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last {0} Battles results.
        /// </summary>
        internal static string TabHeader_LastNBattles {
            get {
                return ResourceManager.GetString("TabHeader_LastNBattles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last week results.
        /// </summary>
        internal static string TabHeader_LastWeek {
            get {
                return ResourceManager.GetString("TabHeader_LastWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last day results.
        /// </summary>
        internal static string TabHeader_Recent {
            get {
                return ResourceManager.GetString("TabHeader_Recent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string TankFilterPanel_All {
            get {
                return ResourceManager.GetString("TankFilterPanel_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage by allies to enemy vehicle you detected: {0}.
        /// </summary>
        internal static string Tooltip_Replay_AlliesDamage {
            get {
                return ResourceManager.GetString("Tooltip_Replay_AlliesDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical damage to enemy vehicle: {0}.
        /// </summary>
        internal static string Tooltip_Replay_CriticalDamage {
            get {
                return ResourceManager.GetString("Tooltip_Replay_CriticalDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage to enemy vehicle: {0}.
        /// </summary>
        internal static string Tooltip_Replay_Damage {
            get {
                return ResourceManager.GetString("Tooltip_Replay_Damage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You detected this enemy vehicle.
        /// </summary>
        internal static string Tooltip_Replay_Detected {
            get {
                return ResourceManager.GetString("Tooltip_Replay_Detected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0.00} km.
        /// </summary>
        internal static string Traveled_Format {
            get {
                return ResourceManager.GetString("Traveled_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t find player data in dossier cache.
        /// </summary>
        internal static string WarningMsg_CanntFindPlayerDataInDossierCache {
            get {
                return ResourceManager.GetString("WarningMsg_CanntFindPlayerDataInDossierCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify player name before.
        /// </summary>
        internal static string WarningMsg_SpecifyPlayerName {
            get {
                return ResourceManager.GetString("WarningMsg_SpecifyPlayerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auth failure.
        /// </summary>
        internal static string WindowCaption_AuthFailure {
            get {
                return ResourceManager.GetString("WindowCaption_AuthFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string WindowCaption_Error {
            get {
                return ResourceManager.GetString("WindowCaption_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string WindowCaption_Information {
            get {
                return ResourceManager.GetString("WindowCaption_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pack.
        /// </summary>
        internal static string WindowCaption_Pack {
            get {
                return ResourceManager.GetString("WindowCaption_Pack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Clan.
        /// </summary>
        internal static string WindowCaption_SearchClan {
            get {
                return ResourceManager.GetString("WindowCaption_SearchClan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Player.
        /// </summary>
        internal static string WindowCaption_SearchPlayer {
            get {
                return ResourceManager.GetString("WindowCaption_SearchPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select path to WorldOfTanks.exe.
        /// </summary>
        internal static string WindowCaption_SelectPathToWorldOfTanksExecutable {
            get {
                return ResourceManager.GetString("WindowCaption_SelectPathToWorldOfTanksExecutable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string WindowCaption_Warning {
            get {
                return ResourceManager.GetString("WindowCaption_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        internal static string WondowCaption_Export {
            get {
                return ResourceManager.GetString("WondowCaption_Export", resourceCulture);
            }
        }
    }
}
