namespace WotDossier.Domain.Player
{
    public class Achievements
    {
        public int medal_dumitru;
        public int invader;
        public int medal_lehvaslaiho;
        public int warrior;
        public int medal_halonen;
        public int medal_pascucci;
        public int medal_orlik;
        public int medal_brothers_in_arms;
        public int mousebane;
        public int tank_expert_france;
        public int mechanic_engineer_ussr;
        public int medal_bruno_pietro;
        public int medal_delanglade;
        public int lucky_devil;
        public int defender;
        public int armor_piercer;
        public int medal_kay;
        public int supporter;
        public int mechanic_engineer;
        public int steelwall;
        public int max_sniper_series;
        public int medal_knispel;
        public int medal_boelter;
        public int medal_ekins;
        public int medal_heroes_of_rassenay;
        public int medal_tamada_yoshio;
        public int tank_expert_usa;
        public int mechanic_engineer_germany;
        public int max_piercing_series;
        public int tank_expert;
        public int iron_man;
        public int medal_radley_walters;
        public int kamikaze;
        public int tank_expert_germany;
        public int beasthunter;
        public int sniper;
        public int medal_tarczay;
        public int medal_lavrinenko;
        public int mechanic_engineer_france;
        public int medal_oskin;
        public int medal_burda;
        public int medal_billotte;
        public int huntsman;
        public int hand_of_death;
        public int medal_fadin;
        public int medal_lafayette_pool;
        public int max_killing_series;
        public int tank_expert_china;
        public int mechanic_engineer_usa;
        public int medal_kolobanov;
        public int patton_valley;
        public int bombardier;
        public int medal_abrams;
        public int max_invincible_series;
        public int medal_poppel;
        public int medal_crucial_contribution;
        public int raider;
        public int max_diehard_series;
        public int mechanic_engineer_uk;
        public int invincible;
        public int lumberjack;
        public int sturdy;
        public int title_sniper;
        public int sinai;
        public int diehard;
        public int medal_carius;
        public int medal_le_clerc;
        public int tank_expert_ussr;
        public int evileye;
        public int mechanic_engineer_china;
        public int medal_nikolas;
        public int scout;
        //added in 0.8.11
        public int sniper2;
        public int main_gun;

        public int marksOnGun;
        public int movingAvgDamage;
        public int medalMonolith;
        public int medalAntiSpgFire;
        public int medalGore;
        public int medalCoolBlood;
        public int medalStark;
    }
}